services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=inbest'
      - 'POSTGRES_PASSWORD=inbest'
      - 'POSTGRES_USER=inbest'
    ports:
      - '5432:5432'
    # Esto es para persistencia, si se borra el contenedor, la bd sigue ahí almacenada
    volumes:
      - postgres-data:/var/lib/postgresql
    # Health checks, comprueba que la bd acepte conexiones
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inbest -d inbest"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: