spring.application.name=inbest
spring.flyway.locations=classpath:db/migration
# Para que JPA no modifique el esquema de la bd, solo flyway
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/inbest
spring.datasource.username=inbest
spring.datasource.password=inbest
